services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: "0:0"
    ports: ["8080:8080","50000:50000"]
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  agent:
    build:
      context: ./agent
      args:
        TF_VERSION: "1.7.5"
        KUBECTL_VERSION: "v1.29.6"
        AWSCLI_VERSION: "2.17.40"
    container_name: jenkins-agent
    depends_on: [jenkins]
    environment:
      JENKINS_URL: http://jenkins:8080/
      AGENT_NAME: docker-agent
      AGENT_SECRET: "REPLACE_WITH_SECRET_FROM_JENKINS"
      AGENT_WORKDIR: /home/jenkins/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
      - ~/.aws:/home/jenkins/.aws:ro
volumes: { jenkins_home: {} }
