pipeline {
  agent { label 'docker-agent' }
  parameters {
    string(name: 'AWS_REGION', defaultValue: 'us-east-1', description: 'AWS region')
    string(name: 'ECR_REPO', defaultValue: '123456789012.dkr.ecr.us-east-1.amazonaws.com/demo/app', description: 'Full ECR repository URI')
    choice(name: 'TAG_STRATEGY', choices: ['git-sha','build-number'], description: 'Tag strategy')
    booleanParam(name: 'PUSH', defaultValue: true, description: 'Push image')
  }
  environment { IMAGE = "${params.ECR_REPO}" }
  stages {
    stage('Checkout'){ steps{ checkout scm } }
    stage('Build'){ steps{ sh 'bash day36-docker-build-push-ecr/scripts/build.sh' } }
    stage('Login to ECR'){ when{ expression{ return params.PUSH } } steps{ sh 'bash day36-docker-build-push-ecr/scripts/login_ecr.sh "${AWS_REGION}" "${IMAGE}"' } }
    stage('Push'){ when{ expression{ return params.PUSH } } steps{ sh 'bash day36-docker-build-push-ecr/scripts/push.sh "${IMAGE}" "${TAG_STRATEGY}"' } }
  }
  post { always { cleanWs() } }
}