pipeline {
  agent { label 'docker-agent' }
  options { timestamps(); ansiColor('xterm'); timeout(time: 20, unit: 'MINUTES') }
  parameters { choice(name: 'ENV_NAME', choices: ['staging','prod']); string(name: 'KUBE_CONTEXT', defaultValue: '') }
  environment { SCRIPTS = 'day57-fluentbit-cloudwatch/scripts' }
  stages {
    stage('Checkout'){ steps { checkout scm } }
    stage('Select Context'){ when { expression { return params.KUBE_CONTEXT?.trim() } } steps { sh 'kubectl config use-context "${KUBE_CONTEXT}"' } }
    stage('Deploy'){ steps { sh 'bash ${SCRIPTS}/deploy.sh ${ENV_NAME}' } }
    stage('Status'){ steps { sh 'bash ${SCRIPTS}/status.sh ${ENV_NAME}' } }
  }
  post { always { cleanWs() } }
}
