pipeline {
  agent { label 'docker-agent' }
  options { timestamps(); ansiColor('xterm'); timeout(time: 20, unit: 'MINUTES') }
  parameters {
    choice(name: 'ENV_NAME', choices: ['staging','prod'])
    string(name: 'IMAGE', defaultValue: 'ealen/echo-server:latest')
    string(name: 'REPLICAS', defaultValue: '')
    string(name: 'KUBE_CONTEXT', defaultValue: '')
  }
  environment {
    SCRIPTS = 'day50-k8s-deployment-service/scripts'
  }
  stages {
    stage('Checkout'){ steps { checkout scm } }
    stage('Select Context'){ when { expression { return params.KUBE_CONTEXT?.trim() } } steps { sh 'kubectl config use-context "${KUBE_CONTEXT}"' } }
    stage('Deploy'){ steps { sh 'bash ${SCRIPTS}/deploy.sh ${ENV_NAME} "${IMAGE}" "${REPLICAS}"' } }
    stage('Rollout'){ steps { sh 'bash ${SCRIPTS}/rollout_status.sh ${ENV_NAME}' } }
  }
  post {
    success { echo "✅ Deployed ${params.IMAGE} to ${params.ENV_NAME}" }
    failure { echo "❌ Deployment failed" }
    always { cleanWs() }
  }
}